### ISSUE TITLE
Breadcrumb doesn't appear when browsing network drives on latest store version

### ISSUE THREAD

**Issue by itsWindows11** [huynhsontung/Screenbox#112]
![image](https://github.com/huynhsontung/Screenbox/assets/81253203/77e70cf4-d396-42c3-9d9f-e5b16e744b30)

**Comment by huynhsontung** [comment]
Thank you for raising this. This is a known bug introduced in the last update. It has been fixed on the main branch and will be in the next update.

https://github.com/huynhsontung/Screenbox/commit/18c8719bc42a0765a4337913c07fea21304f70ae
