### ISSUE TITLE
Can't set Screenbox to open .opus files by default

### ISSUE THREAD

**Issue by OdinIsLord** [huynhsontung/Screenbox#164]
Also, It would be nice if you would release Screenbox as a program rather than a store app in the future. Loving it so far.

**Comment by huynhsontung** [comment]
You can already download a sideload package under [Releases](https://github.com/huynhsontung/Screenbox/releases) if you want to install the app without the Store. Note that you will need to run an install script for the app to be installed successfully.

**Comment by OdinIsLord** [comment]
I meant release as an .exe program, not an app.

**Comment by huynhsontung** [comment]
Unpackaged release would require the app to be migrated to WinAppSDK/WinUI3. This is not currently planned as there are no inherent benefits to having an unpackaged .exe program while adding complexity to the app installation. Are there any particular reasons you wish for the app to be a .exe executable?

**Comment by OdinIsLord** [comment]
Well for one, me opening a whole issue to set a simple file association as default. If it was a .exe program I would just force run anything through it. VLC can read a lot of file associations, so .opus is just one of them. If the UWP was not programmed to open files of a certain type, it cannot be manually added to this list.

Not to mention if you want your work to explode in popularity, it sure as hell won't do it through UWP. All popular programs include a standard installer and a portable zip version. Just my take.

**Comment by huynhsontung** [comment]
I see. Limited file format support is an intentional design decision. However, I do track and add support for more extensions when there is a request.
