### ISSUE TITLE
win11 无法安装，无法验证此应用包的发布者证书

### ISSUE THREAD

**Issue by hhun** [huynhsontung/Screenbox#169]
能不能弄成`exe`格式的安装包
![360截图20231004115439526](https://github.com/huynhsontung/Screenbox/assets/19625243/9979b780-420e-424b-894f-2e0a5207fee6)

**Comment by huynhsontung** [comment]
Hello, Screenbox sideload is only for testing purposes only. You can install the sideload package by running the "Install.ps1" script. The recommended method to install the app is through the [Microsoft Store](https://apps.microsoft.com/store/detail/screenbox-media-player/9NTSNMSVCB5L).

**Comment by cherub0507** [comment]
https://blog.csdn.net/qq_36237810/article/details/110238783

亲测有效

供参考
