### ISSUE TITLE
support .ass subtitle?

### ISSUE THREAD

**Issue by Yusei-StarDust** [huynhsontung/Screenbox#178]
the current version seems not support this type of subtitle format

**Comment by huynhsontung** [comment]
The current version does have support for .ass subtitles. Do you have a particular file that doesn't work?

**Comment by Yusei-StarDust** [comment]
I tried again and just found it seemed to load a bit slower so that i mistook the current version haven't support yet😅...There is no problem now

**Comment by huynhsontung** [comment]
Thank you for confirming. Closing this issue now.
