### ISSUE TITLE
ARM support consider?

### ISSUE THREAD

**Issue by SituChengxiang** [huynhsontung/Screenbox#179]
Hi there, I found that VLC UWP has supported Windows On ARM natively for a period of time, and it works well on my arm pc. I think Screenbox will have a better performance on arm platforms if it can support arm natively.
 Hope to take it into consideration. (If there is anything I can help, please comment.)

**Comment by huynhsontung** [comment]
Hello, thanks for taking an interest in the project. The main issue is [LibVLC doesn't support ARM64](https://code.videolan.org/videolan/libvlc-nuget/-/issues/1). I plan to debug this when I have more demand for ARM64 support. I would appreciate some help on this.

**Comment by SituChengxiang** [comment]
Thnaks for replying, if the issue still exists until 2024/6/10 (I am preparing for China's College Entrance Examination ) , I will try to do that.

**Comment by huynhsontung** [comment]
ARM64 support has been implemented. Testing for ARM64 has been limited due to the lack of dedicated hardware. Please try again and let me know if you encounter any issues. Closing this issue for now.
