### ISSUE TITLE
language

### ISSUE THREAD

**Issue by senolfndk** [huynhsontung/Screenbox#185]
Can you add Turkish language?

**Comment by huynhsontung** [comment]
Hey there, app translation is crowd-sourced through Crowdin. Turkish translation is incomplete so it has not been published yet. Once the translation is complete, the language will be available in the following release. You can help translate [the app to Turkish on Crowdin](https://crowdin.com/project/screenbox/tr).

**Comment by senolfndk** [comment]
I'm not an expert on this subject
