### ISSUE TITLE
auto load subtitle file which has the same name as the video?

### ISSUE THREAD

**Issue by Yusei-StarDust** [huynhsontung/Screenbox#190]
The current version seems not to support this feature...？

**Comment by Yusei-StarDust** [comment]
seems ... not to work😥

**Comment by huynhsontung** [comment]
Sorry, I forgot to clarify. It should load the subtitle but not select it by default. The subtle will be available to select in the subtitle picker right away, instead of having to browse for the subtitle file. This is inline with the default media player behavior. Let me know if this is not the case for you.

**Comment by Yusei-StarDust** [comment]
![issue_step1](https://github.com/huynhsontung/Screenbox/assets/26076608/f90e7459-87a2-48fa-a38f-f14c437b4d4a)
![issue_step2](https://github.com/huynhsontung/Screenbox/assets/26076608/84e26639-a146-45bd-bdd4-d69591d2b201)
My English expression is not very good. If the grammar is wrong or the wording is not very polite, please forgive me.
In my case, still having to manually add the subtitle in the explorer rather than select in the in-build picker.

**Comment by huynhsontung** [comment]
No worries. I just need one more piece of information. Did you open the video file from Explorer or did you open it from inside the app (using the app picker or through the Videos page)?

**Comment by Yusei-StarDust** [comment]
Both way I had tried, but neither loaded the subtitle in the inline picker.

**Comment by huynhsontung** [comment]
Can you let me know where the file is located on your computer? Is it in your videos library, or in a network location, or in a USB/external hard drive, or just a random location in your computer?

I suspect the app can't see the whole folder due to permission restrictions. Would you mind copying the video and subtitle to a folder in your Videos library and try opening it from there?

**Comment by Yusei-StarDust** [comment]
I had tried several different location(C:\Users\user\Videos, C:\Users\user\Downloads, cloud drive etc), even uninstalled and reinstall this program, but still don't work.

**Comment by huynhsontung** [comment]
Thank you so much for your help. This seems more complicated than I expected. I will look into this issue and keep you posted.

**Comment by GuaiYiHu** [comment]
> Can you let me know where the file is located on your computer? Is it in your videos library, or in a network location, or in a USB/external hard drive, or just a random location in your computer?
> 
> I suspect the app can't see the whole folder due to permission restrictions. Would you mind copying the video and subtitle to a folder in your Videos library and try opening it from there?

Thanks to your fantastic project. I found the subtitle loaded automaticly when it was located in my local disk, but It fails to load when it's on my NAS. Could you fix it, plz?

**Comment by GuaiYiHu** [comment]
@huynhsontung I found this is a permission issue... I'm modifying the related code these days and managed to load subtitles on my nas by added the file access permission.
See: https://learn.microsoft.com/zh-cn/windows/uwp/files/file-access-permissions#example

**Comment by huynhsontung** [comment]
@GuaiYiHu That is correct. It is generally a permission issue. However, granting the app more permissions is not the solution. Especially `broadFileSystemAccess` may make the store certification process harder. The workaround I used in #353 is an API that can look into the neighbouring files in the same directory. This API is not available in all use cases but it should work in most common cases.

**Comment by GuaiYiHu** [comment]
@huynhsontung greate job! This is the best media player ever on UWP!
I'm adding other features which are more suitable for myself:
1. Automatically play the next video in the same folder when sequential playback is turned on.
2. Optimize the video click event behavior after turning off the "close click on video area" switch.

**Comment by huynhsontung** [comment]
@GuaiYiHu Just FYI, the app can already load the next video in the same folder. It just doesn't play them automatically. You can click the Next button or `Page Down` to load the next file. I have no plan to customize this behavior yet.

Please open new issues for feature requests. I appreciate it. 🙏

**Comment by GuaiYiHu** [comment]
> @GuaiYiHu Just FYI, the app can already load the next video in the same folder. It just doesn't play them automatically. You can click the Next button or `Page Down` to load the next file. I have no plan to customize this behavior yet.
> 
> Please open new issues for feature requests. I appreciate it. 🙏

Tested subtitle, didn't fix... This is my fix https://github.com/GuaiYiHu/Screenbox/commit/4793fc73b6ddbc8fa2097c5760f17c874291d3b1

**Comment by GuaiYiHu** [comment]
@huynhsontung I'm not familiar with UWP development but I added some shity changes which satisfy my needs in my branch https://github.com/GuaiYiHu/Screenbox/tree/yexiao_dev

**Comment by huynhsontung** [comment]
@GuaiYiHu Did you test the subtitle fix with the latest changes in the main branch? I see your fix was based on the code before the fix. Plus you had `broadFileSystemAccess` permission on your branch.

**Comment by Welding-Torch** [comment]
> Sorry, I forgot to clarify. It should load the subtitle but not select it by default. The subtle will be available to select in the subtitle picker right away, instead of having to browse for the subtitle file.
@huynhsontung 

Hey, can you change this so that the subtitle is actually selected by default and not load available in the subtitle picker? It is a chore to have to pick the subtitle from the picker 100s of times. Please make this change.
