### ISSUE TITLE
lagging and stuttering

### ISSUE THREAD

**Issue by Ilyas729** [huynhsontung/Screenbox#193]
when I play a video, it sometimes happens  like it was in VLC, I solved that problem by  increasing file cash to 2000 but in your program, I couldn't find that function .

**Comment by huynhsontung** [comment]
Hello, can you try enabling "Advanced mode" in settings and then add `--file-caching=2000` to the "Global arguments"?

**Comment by Ilyas729** [comment]
ok thanks
