### ISSUE TITLE
Empty music library with v0.10.0

### ISSUE THREAD

**Issue by Armin2208** [huynhsontung/Screenbox#207]
**Describe the bug**
After the update to v0.10.0 via Microsoft Store, my music library is empty. Screenbox says "We couldn't find any music".
![grafik](https://github.com/huynhsontung/Screenbox/assets/32982430/f9dd4fde-b3f6-4b09-87fe-7f7fda528e3c)

Although in app settings my music folder is still listed as music library location.
![grafik](https://github.com/huynhsontung/Screenbox/assets/32982430/745fb927-05b1-40d7-94d2-879765025be8)

And Screenbox has the needed permissions on Windows 11.
![grafik](https://github.com/huynhsontung/Screenbox/assets/32982430/21f446cc-50a7-491c-998d-024426879df9)

So I tried to remove the music folder and re-added it. But still after doing this my music library is empty.

**Environment**

 - OS: Windows 11 Pro (22621.2428)
 - Device: Desktop-PC
 - App Version v0.10.0

**Comment by huynhsontung** [comment]
Strange. I didn't touch any library processing logic. I can't find any reason for this issue to occur. Can you try to reinstall the app?

**Comment by Armin2208** [comment]
Hey @huynhsontung. I reinstalled Screenbox. And I can confirm my settings were reset, so the configuration from previous install wasn't restored.

Sadly Screenbox still doesn't find any song in my music library. It's empty.

**Comment by huynhsontung** [comment]
@Armin2208 just to confirm, the music library is still available in the default Media Player right? This issue is isolated to Screenbox only?

**Comment by Armin2208** [comment]
That's the case. I even added a new song to my library, seeing if Media Player is recognizing this change. it did, the new song is in my library on Media Player. 

ANNND Holy fuck. The song even appeared in my music library in Screenbox. It now contains this one new song. That's a reaaallly weird behavior. So it kinda can scan the folder, but it's missing all of my "old" albums.

**Comment by huynhsontung** [comment]
Woa this is very interesting. This might be an indexer issue. I will add an option to disable the indexer for scanning in the next update to see if that fixes it.

**Comment by huynhsontung** [comment]
Option to disable indexer is implemented in #214

**Comment by huynhsontung** [comment]
V0.10.1 with this feature is now available in the store. Can you try again but with the "Use indexer" option disabled in the settings?

**Comment by Armin2208** [comment]
> V0.10.1 with this feature is now available in the store. Can you try again but with the "Use indexer" option disabled in the settings?

Hello @huynhsontung. Thanks for implementing the new feature as a fix. I did disable indexer for scanning and now my whole music library is back in Screenbox. Awesome!!!
Maybe toggling the index toggle should do a refresh.

**Comment by huynhsontung** [comment]
> Maybe toggling the index toggle should do a refresh.

I think they have two separate functions. Indexer is a child option of the Refresh action so I don't think refreshing on toggle change is very intuitive.

**Comment by Armin2208** [comment]
> I think they have two separate functions. Indexer is a child option of the Refresh action so I don't think refreshing on toggle change is very intuitive.

This is a good example of two persons having a different view or feel of intuitive stuff :D 

For me, it's not intuitive to toggle an option to just see... no effect. I kinda expect the refresh is done for me. 

The first time I toggled the option, i did go into the library and saw no changes. So I needed to go back to settings, just to click refresh.

You can close this issue, if you don't want to add the auto refresh after toggling.

**Comment by huynhsontung** [comment]
We can certainly improve the readability of this option in some way. I also see where you are coming from as well. I will do a bit of a prototype to see how that feels. However, the UX change is outside the scope of this issue so I'm closing it now. Thank you for your feedback!
