### ISSUE TITLE
Scrolling on seekbar to seek the video

### ISSUE THREAD

**Issue by sayyid5416** [huynhsontung/Screenbox#210]
**> Is your feature request related to a problem? Please describe.**
Not really an issue, but this feature is available in VLC player, and I use this feature a lot.

**> Describe the solution you'd like**
Implement the feature to seek the video backward and forward when user scrolls on player seekbar using mouse scroll.

**> Additional context**
I just installed this app _(Screenbox)_ for the first time, and **honestly** I love it. Only thing which seems missing is this feature, So I personally think it would be a great feature to implement.

**Comment by huynhsontung** [comment]
Thank you for your feedback. I'm glad that you like it. Scrolling on the seek bar will be a good addition to the gesture options. Since we already have scrolling inside the video player to change the volume, I think this gesture should be off by default to avoid confusion. Other than that, I'm all in for this feature.

**Comment by sayyid5416** [comment]
Gestures in the app are used like "press and hold left mouse button and then sliding."

What I want is scrolling using the mouse scroll wheel, so that I can place the cursor on anywhere on seekbar and scroll back and forth without going to the current playhead.

I don't know if I'm able to explain this properly or not, but I'll attach the video soon.

**Comment by sayyid5416** [comment]
https://github.com/huynhsontung/Screenbox/assets/78584556/eeaeb60b-81a2-40db-b5e5-f0c6bbace792

I used scroll wheel of mouse for the scrolling purpose. I hope I was able to explain it properly.

**Comment by United600** [comment]
> I used scroll wheel of mouse for the scrolling purpose. I hope I was able to explain it properly.

TBH, while it can be useful to someone, I wouldn't introduce this option (at least by default).
Two competing vertical scrolls on the same page isn't ideal (and not recommended iirc).

**Comment by sayyid5416** [comment]
> I wouldn't introduce this option (at least by default).

Fine by me. As long as option is available.

<br>

> Two competing vertical scrolls on the same page isn't ideal (and not recommended iirc).

But Doesn't VLC have this functionality! vertical scrolling on playback area and vertical scrolling on seekbar are two different things. How's that competing?
