### ISSUE TITLE
Captions are buggy

### ISSUE THREAD

**Issue by KParthSingh** [huynhsontung/Screenbox#235]
**Describe the bug**
Subtitles appear even if disabled in the menu.

**How To Reproduce**
Just use it like usual.

**Expected behavior**
Subtitles should not be displayed.

**Video**
https://drive.google.com/file/d/1l5-zAZZULMqqhcUaLz_eRj-5l5BXZ8_c/view?usp=sharing

**Environment**

 - OS: Windows 11
 - Device: Custom build pc
 - App Version v0.10.1

**Additional context**
None

**Comment by Mitia99** [comment]
I also noticed that the caption feature is buggy. Don't know how to reproduce the issue.
Btw, @huynhsontung it will be great to display full language name with first letter in uppercase instead of only `eng` `fre` etc... ISO code

**Comment by United600** [comment]
> I also noticed that the caption feature is buggy. Don't know how to reproduce the issue. Btw, @huynhsontung it will be great to display full language name with first letter in uppercase instead of only `eng` `fre` etc... ISO code

AFAIK the name is set at the file level and then retrieved.

A recent LibVLC update brought some bugs and unintended changes.

**Comment by Mitia99** [comment]
> > I also noticed that the caption feature is buggy. Don't know how to reproduce the issue. Btw, @huynhsontung it will be great to display full language name with first letter in uppercase instead of only `eng` `fre` etc... ISO code
> 
> AFAIK the name is set at the file level and then retrieved.
> 
> A recent LibVLC update brought some bugs and unintended changes.

I played the same media with other media players and it's displayed as `English` `French` in caption menu.

**Comment by United600** [comment]
> > > I also noticed that the caption feature is buggy. Don't know how to reproduce the issue. Btw, @huynhsontung it will be great to display full language name with first letter in uppercase instead of only `eng` `fre` etc... ISO code
> > 
> > 
> > AFAIK the name is set at the file level and then retrieved.
> > A recent LibVLC update brought some bugs and unintended changes.
> 
> I played the same media with other media players and it's displayed as `English` `French` in caption menu.

As you can see it retrieves the info from the file: Name (Language)

![image](https://github.com/huynhsontung/Screenbox/assets/698155/2cf9c790-6de1-4d33-b6d5-76db899c3d2b)
![image](https://github.com/huynhsontung/Screenbox/assets/698155/4324b2a0-2d0a-4d76-ba32-a3e32093bbf1)

**Comment by Mitia99** [comment]
> > > > I also noticed that the caption feature is buggy. Don't know how to reproduce the issue. Btw, @huynhsontung it will be great to display full language name with first letter in uppercase instead of only `eng` `fre` etc... ISO code
> > > 
> > > 
> > > AFAIK the name is set at the file level and then retrieved.
> > > A recent LibVLC update brought some bugs and unintended changes.
> > 
> > 
> > I played the same media with other media players and it's displayed as `English` `French` in caption menu.
> 
> As you can see it retrieves the info from the file: Name (Language)
> 
> ![image](https://user-images.githubusercontent.com/698155/284011184-2cf9c790-6de1-4d33-b6d5-76db899c3d2b.png) ![image](https://user-images.githubusercontent.com/698155/284011206-4324b2a0-2d0a-4d76-ba32-a3e32093bbf1.png)

I think there is a misunderstanding. I'm not talking about languages available to display but how it is displayed (check edited previous comment).

**Comment by United600** [comment]
![image](https://github.com/huynhsontung/Screenbox/assets/698155/9f41b0e8-6cce-4827-b772-a9c9d7d6f435)

I see, VLC UWP converts the language field. I think we can do that too.

**Comment by United600** [comment]
> I think there is a misunderstanding. I'm not talking about languages available to display but how it is displayed (check edited previous comment).

No I understood you, I was just saying that Screenbox reads->displays the info from the file.

**Comment by huynhsontung** [comment]
> I see, VLC UWP converts the language field. I think we can do that too.

We would need to localize language names as well in this case. I wonder if there is any library for this task.

**Comment by United600** [comment]
> > I see, VLC UWP converts the language field. I think we can do that too.
> 
> We would need to localize language names as well in this case. I wonder if there is any library for this task.

Right, didn't think about that. Maybe it's not worth the effort after all and leave it to the file metadata.

Mmm, curiously "eng" is being replaced by "English".

**Comment by KParthSingh** [comment]
*coughs* It deeply pains me to express the profound disappointment and sorrow that shrouds my being upon realizing that my meticulously crafted, heartfelt inaugural bug report has been tragically consigned to the realms of neglect and disregard. The weight of this dismissal, a creation stemming from the depths of my heartfelt dedication, this flagrant disregard for my earnest contribution, hangs heavily upon my spirit, casting a shadow upon my very soul, leaving me awash in desolation and sorrow.

 *Doth weepeth in yonder corner's embrace* *

**Comment by huynhsontung** [comment]
@KParthSingh Haha I'm still tracking the original issue. Don't worry. Sometimes VLC auto selects a subtitle but the UI is not updated. It's a bug on the Screenbox side.

I plan to let VLC continue to decide when to auto select a subtitle and just fix the UI so it updates correctly.

**Comment by KParthSingh** [comment]
bruh i was just bored.
