### ISSUE TITLE
certificate error

### ISSUE THREAD

**Issue by senolfndk** [huynhsontung/Screenbox#24]
not loading 🤔
![Ekran görüntüsü 2023-02-20 202830](https://user-images.githubusercontent.com/52818836/220171061-6d2c68a4-9190-462a-862d-fc81005fefd2.png)

**Comment by senolfndk** [comment]
I am not loaded again, I registered, I wait for the Microsoft Store beta version

**Comment by huynhsontung** [comment]
I have added you to the private testing group. You can download the app using [this link](https://www.microsoft.com/store/r/9NTSNMSVCB5L). The open beta will be the same listing but open for everyone (no authentication requires).

**Comment by senolfndk** [comment]
music playback problem 😒
https://user-images.githubusercontent.com/52818836/220302808-9bbbdb28-9594-49d4-9f2d-d40261e887f5.mp4

**Comment by senolfndk** [comment]
music playback problem 😒

https://user-images.githubusercontent.com/52818836/220304188-8e4d866c-8e57-47f5-a5ff-3734f41c55e7.mp4

**Comment by huynhsontung** [comment]
[v0.8.3](https://github.com/huynhsontung/Screenbox/releases/tag/v0.8.3) should fix this issue. Please try again and let me know.

**Comment by senolfndk** [comment]
> [v0.8.3](https://github.com/huynhsontung/Screenbox/releases/tag/v0.8.3) bu sorunu çözmelidir. Lütfen tekrar deneyin ve bana bildirin.

ok it's ok
