### ISSUE TITLE
Buggy Space hotkey - Play/Pause

### ISSUE THREAD

**Issue by Mitia99** [huynhsontung/Screenbox#242]
**Describe the bug**
Buggy Space hotkey

**Steps to reproduce the behavior:**
1. Play a video
2. Click on `Audio & Captions` or the `...` button
3. Click on video screen (to leave the Audio & Captions menu)
4. Click `Space` to pause

**Expected behavior**
Pause the video

**Environment**
 - OS: Windows 11 23H2 Build 22631.2715
 - App Version: 0.10.2

**Additional context**

- An other click is needed after step 3 to fix the issue.
- There4S no such issue with [VLC UWP](https://www.microsoft.com/store/productId/9NBLGGH4VVNH?ocid=pdpshare)
- There is a related issue with `Picture-in-Picture` and `Fullscreen` button , Space hotkey should pause the video after entering these modes without clicking the video like in VLC UWP

Thanks for investigating,

**Comment by KParthSingh** [comment]
This bug really annoys me, I thought it was intentional for some reason. @huynhsontung please fix it.

**Comment by huynhsontung** [comment]
It was kinda intentional. The Space key is also a universal interaction key for Windows controls (along with Enter) so overriding it may confuse users who rely on the keyboard for navigation. But the default Media Player overrides it so why not.

Implemented in #252

**Comment by KParthSingh** [comment]
This is off topic, but do you know of any solution out there for youtube?

**Comment by huynhsontung** [comment]
> This is off topic, but do you know of any solution out there for youtube?

Not that I aware of. I imagine they intentionally set it like that for the same reason.

**Comment by KParthSingh** [comment]
i found a solution: https://www.reddit.com/r/youtube/comments/15281c4/comment/k6hkff9/?utm_source=share&utm_medium=web2x&context=3 ;)

**Comment by huynhsontung** [comment]
AI strikes again bruh
