### ISSUE TITLE
Refresh libraries received no translation (pt-BR)

### ISSUE THREAD

**Issue by maisondasilva** [huynhsontung/Screenbox#249]
I noticed that Refresh libraries received no translation, although the translation file has these translated variables, is this known?
Congratulations on your project, it's great!
I made some corrections to the old translations of my language.

![image](https://github.com/huynhsontung/Screenbox/assets/11423362/92f3f3d3-d30d-4a6f-aad2-1d21771e0f77)

and

![image](https://github.com/huynhsontung/Screenbox/assets/11423362/2874a07f-f336-47e8-8578-3684cb3f3599)

Thanks Maison

**Comment by United600** [comment]
Probably wasn't translated before the last release. Your updates will appear in the next release. Thanks.

**Comment by United600** [comment]
Oh and the "[Set Arguments](https://github.com/huynhsontung/Screenbox/blob/main/Screenbox/Pages/SettingsPage.xaml#L295)" button needs localization, thanks we missed that one.

**Comment by maisondasilva** [comment]
@United600 Thanks for the update, I'm testing it on all my clients who use VLC as an alternative, thanks for this excellent project!
I only miss the Visualization effects for audio, will this be possible to implement?

**Comment by maisondasilva** [comment]
As soon as you send the "Set arguments" translation in Crowdin, let me know so I can translate it, I made some polishes to the translation.

**Comment by maisondasilva** [comment]
Done ✅
