### ISSUE TITLE
In settings, minimize or maximize options are not saved when closing the program and opening it again

### ISSUE THREAD

**Issue by maisondasilva** [huynhsontung/Screenbox#262]
I don't know if this is a bug, or if it's expected, nothing important but I'm just reporting
This happens with all menus that have this option!

Example 

![image](https://github.com/huynhsontung/Screenbox/assets/11423362/a1e78cdf-a113-4670-a2b5-5d92fd8845ee)

after closed and open show opened

![image](https://github.com/huynhsontung/Screenbox/assets/11423362/e154b212-8f3e-494f-ae01-af2344f6283c)

**Comment by United600** [comment]
That card is expanded by default and not saved between sessions/navigation, honestly we probably shouldn't have expanded cards by default but, as of right now, we have only a couple of them.

**Comment by huynhsontung** [comment]
Changed in #314. Cards are now closed by default.
