### ISSUE TITLE
Request for Winget Source Installation Support for Screenbox

### ISSUE THREAD

**Issue by animegamer4422** [huynhsontung/Screenbox#307]
#### Is your feature request related to a problem? Please describe.

I've encountered an issue with the current installation process for Screenbox. Presently, Screenbox can be installed via Winget through the Microsoft Store, but it lacks support for the direct Winget command `winget install screenbox -s=winget`. This limitation affects users like me who prefer the straightforwardness and efficiency of using Winget directly with the `-s=winget` source specifier.

#### Describe the solution you'd like

My proposed solution is for Screenbox to support the specific Winget command `winget install screenbox -s=winget`. This command allows users to install Screenbox directly, bypassing the Microsoft Store, and provides a more streamlined and consistent experience for those who regularly use Winget as their primary software management tool.

#### Describe alternatives you've considered

Currently, I resort to installing Screenbox via the Microsoft Store using Winget. However, this approach is not ideal for my workflow, which relies on the simplicity and directness of using Winget with the `-s=winget` source specifier for all my software installations. The integration of this specific command would greatly enhance efficiency and user experience.

#### Additional context

Supporting the `winget install screenbox -s=winget` command could significantly improve the installation process for many users. This enhancement aligns with the growing trend of utilizing command-line tools for software management and could potentially increase Screenbox's popularity among tech-savvy users and in professional environments that prioritize efficient software management practices.

**Comment by huynhsontung** [comment]
Thank you for the suggestion. I would personally love to allow for more methods of installation. Unfortunately, deploying a UWP outside the store requires the app package to be digitally signed. Signing certificates can be very expensive and thus completely non-viable for an open-source project like Screenbox. This is also why I don't publish a proper package on GitHub for each release but just a sideload package for testing.

**Comment by animegamer4422** [comment]
No worries
You've built an amazing app and that's more than enough for me :)
