### ISSUE TITLE
Support for Winget.

### ISSUE THREAD

**Issue by KParthSingh** [huynhsontung/Screenbox#327]
**Is your feature request related to a problem? Please describe.**
Screenbox is not available on Winget.

**Describe the solution you'd like**
Please submit Screenbox to Winget. I attempted to do it myself, but I couldn't because I'm not a developer.

**Comment by United600** [comment]
![Terminal snippet](https://github.com/huynhsontung/Screenbox/assets/698155/f7a5d852-109c-4e2d-9e6c-2f6bcf41740e)

It's already available (although kinda annoying having to use the full package name), you can type:
```
winget install "screenbox media player"
```
or
```
winget install 9NTSNMSVCB5L
```

**Comment by KParthSingh** [comment]
Could you please just make it Screenbox? It will not be available in Winget for people like me. Aside from the fact that they are aware that it is called "screenbox media player"

**Comment by KParthSingh** [comment]
uh also
C:\Users\K.Parth>winget install screenbox media player
No package found matching input criteria.
Package not found: screenbox
No package found matching input criteria.
Package not found: media
No package found matching input criteria.
Package not found: player

C:\Users\K.Parth>winget install "screenbox media player"
No package found matching input criteria.

C:\Users\K.Parth>winget install 9NTSNMSVCB5L
No package found matching input criteria.

**Comment by United600** [comment]
Can you check what version and sources you have?
```powershell
winget source list
```
```powershell
winget -v
``` 
![Powershell commads](https://github.com/huynhsontung/Screenbox/assets/698155/01acf83f-7fc1-46b3-ad57-2cb14324dfc4)
Just tried on a clean environment and worked as expected.
![Showing the recent app installed](https://github.com/huynhsontung/Screenbox/assets/698155/a404ecd9-4bd5-4540-aac6-51de12394c51)

**Comment by KParthSingh** [comment]
> Just tried on a clean environment and worked as expected.
is it than because i removed msstore source?

I'm using v1.6.3482 and
winget source list
Name   Argument
---------------------------------------------
winget https://cdn.winget.microsoft.com/cache

**Comment by United600** [comment]
> Is it because I removed msstore source?
> 

Pretty sure that's the issue

**Comment by KParthSingh** [comment]
> Pretty sure that's the issue.

I added msstore source to check and it worked also it finds the package just by `screenbox` which it couldn't do before.
