### ISSUE TITLE
App Installer failed to install package dependencies. Ask the developer for  package

### ISSUE THREAD

**Issue by 3052** [huynhsontung/Screenbox#335]
https://github.com/huynhsontung/Screenbox/releases/tag/v0.12.1

**Comment by huynhsontung** [comment]
Hi, the recommended method to install the app is through the [Microsoft Store](https://www.microsoft.com/store/apps/9NTSNMSVCB5L?cid=storebadge&ocid=badge). The sideload package in the release is for validation purposes only. If you still wish to install the app without the Store, please download the sideload package and execute the `Install.ps1` script.

**Comment by 3052** [comment]
turns out I dont need this anymore. I was searching for something that would handle TTML, which VLC does, and by extension Screenbox should as well.

however TTML support in VLC is pretty shitty, where generally the text timing doesnt match up with the video/audio. I also found that so far at least the sites I am using also offer WebVTT, which seems to have a much better experience overall, so I am going with that for now
