### ISSUE TITLE
Missing Picture In Picture Icon|Glyph

### ISSUE THREAD

**Issue by D-Maxwell** [huynhsontung/Screenbox#339]
**Describe the bug**
On Win10, the Picture-in-picture button does not appear to find any matching glyph.
I suspect that this is a Win11 exclusive glyph, as many other apps made with Win11 in mind suffer from similar issues when ran on Win10.

**How To Reproduce**
Play any file
Witness

**Expected behavior**
The null glyph currently shown should be correctly substituted for its intended one.

**Screenshots**
![image](https://github.com/huynhsontung/Screenbox/assets/98100481/d48ac191-6075-4cf7-9a3a-7408830ec5e6)

**Environment**
 - OS: Windows 10 Pro 22H2 19045.2788
 - Device: PC (x86_64, AMD CPU, NVIDIA GPU)
 - App Version: 0.12.1.0

**Additional context**
The app was installed through the `sideload.zip` archive provided in releases.

**Comment by United600** [comment]
Known issue, fixed (#316) in the next version.
