### ISSUE TITLE
Cast to a device never finds Chromecast

### ISSUE THREAD

**Issue by HobNoxious** [huynhsontung/Screenbox#345]
Windows 11 Home 24H2
Latest release installed from Windows Store.
Chromecast Gen 3

Ctrl-K / "Cast to a device" never finds the Chromecast
VLC Player does find the Chromecast and can stream to it.
![image](https://github.com/huynhsontung/Screenbox/assets/137054185/f3aaf777-4451-4272-9bc2-467a838aa342)

**Comment by huynhsontung** [comment]
Thank you for the report. Confirmed Chromecast stopped working from v0.12.1 onward. Seems to be an issue with the custom libvlc build.

Caused by: https://github.com/huynhsontung/libvlc-nuget/pull/7

Attempt to fix: https://github.com/huynhsontung/libvlc-nuget/pull/16

**Comment by HobNoxious** [comment]
I can confirm, reverting to 0.12.0 via sideload has fixed the Cast issue. My Chromecast is now found and I can cast music and movies to it.
