### ISSUE TITLE
.qt video file does not display video

### ISSUE THREAD

**Issue by DogancanYr** [huynhsontung/Screenbox#346]
![resim](https://github.com/huynhsontung/Screenbox/assets/90002969/90b258ab-b6fa-4720-a9be-34fbfa379787)
[SPOILER_alwaysmyniga.qt.txt](https://github.com/huynhsontung/Screenbox/files/14733347/SPOILER_alwaysmyniga.qt.txt)
Delete the .txt text at the end. Github did not allow me to upload .qt file.

**Comment by DogancanYr** [comment]
It works in vlc.

**Comment by huynhsontung** [comment]
I did not know .qt is a QuickTime video extension. As a workaround, can you change the extension to .mov and try again?

**Comment by DogancanYr** [comment]
When I change it, there is no problem (mp4 or mov). I also noticed that github changed the extension.

**Comment by huynhsontung** [comment]
Actually, this was caused by another issue that incorrectly sets the media type of a file. Fixed in #347
