### ISSUE TITLE
Bug in latest version

### ISSUE THREAD

**Issue by sayyid5416** [huynhsontung/Screenbox#348]
https://github.com/huynhsontung/Screenbox/assets/78584556/35a32d64-ac23-4863-90c9-14c37e8d19f9

**Comment by huynhsontung** [comment]
Thanks for reporting, I have fixed that bug yesterday in #347. Publishing a new version now.

**Comment by huynhsontung** [comment]
Should be fixed in v0.12.4. Please update the app and try again.

**Comment by sayyid5416** [comment]
yup. it's now fixed.
