### ISSUE TITLE
Screen Box Not Running In Window 10

### ISSUE THREAD

**Issue by Rupesh9369** [huynhsontung/Screenbox#359]
**Describe the bug**

when i start the app automatic Crash The App not open Any video in this app and when i click to start app they show popup open window but after 4 sec app crash and close down 

**How To Reproduce**

**Expected behavior**

**Screenshots**

https://github.com/huynhsontung/Screenbox/assets/128808356/5f28771c-9b92-4200-bcdb-f8314a98be57

**Environment**

 - OS: [e.g. Windows 10]
 - Device: [Laptop Lenovo ThinkPad  ]
 - App Version [e.g. v0.12.05]

**Additional context**

**Comment by huynhsontung** [comment]
From my crash report, I think your machine does not have a graphic driver capable of Direct3D11, which is very weird. Do you mind updating your graphic driver from the [Intel website](https://www.intel.com/content/www/us/en/download-center/home.html)? (I assume you have an integrated Intel graphics card)
