### ISSUE TITLE
In some of videos in the youtube link, it only plays the audio track (no video).

### ISSUE THREAD

**Issue by vladkryv** [huynhsontung/Screenbox#364]
**Describe the bug**
In **some** videos on youtube link, only the audio track (without video) is played. VLC player plays them normally.

**How To Reproduce**
1. Open ScreenBox
2. Select "Open URL" from the drop-down list in the upper right corner
3. Enter "https://youtu.be/dp-3m-B95sU" and press OK, then wait.
4. See that only audio is playing

**Expected behavior**
Normal playing audio and video, like in VLC.

**Screenshots**
<details>
  <summary>Spoiler</summary>

![scr](https://github.com/huynhsontung/Screenbox/assets/83036866/7c48c06a-8bd6-4d50-8b13-42544ee1946c)
</details>

**Environment**
 - Windows 11
 - Asus Laptop
 - App Version v0.12.5.0

**Additional context**
It doesn't happen with all youtube videos, some of them play fine, I haven't looked for a pattern.

**Comment by huynhsontung** [comment]
Hello, after some testing, I found out that the video parsing timeout before it can parse a video stream from YouTube and mistakenly label it as an audio-only stream. I will increase the parsing timeout duration and make sure it successfully fetches the data before labelling the media type.
