### ISSUE TITLE
Various sorting options for albums/artists, etc.

### ISSUE THREAD

**Issue by utilop** [huynhsontung/Screenbox#370]
I think I'm not the only one who prefers a compact view of the media library, not based on the newfangled sorting by first letters. To be honest, I hate it... It’s convenient for me to navigate by the labels. For example, sort albums by date added. This makes it easier to remember what is where. It is often impossible to remember the name of the album... and when you come to scroll through a long list.
 There is such a function in the Windows music player and you can attach it. Unfortunately, even there it is impossible to make sure that when you click on the “Music” item, it opens the albums and not the tracks in the described order. (Although now I thought that it would be more logical for the tracks to open, since this is music) So the second point is at your discretion.
  As an idea, you can place the search by letters (the letters themselves) on the left, rather than separating them.

**Comment by nobef** [comment]
@huynhsontung Thanks for adding the feature! But I would like the application to remember this parameter. Well, like in a standard “media player”
