### ISSUE TITLE
Doesn't work anymore on Windows 11 the application closes unexpectedly when opened

### ISSUE THREAD

**Issue by toohug866** [huynhsontung/Screenbox#383]
**Describe the bug**

The application closes unexpectedly when opened
**How To Reproduce**

1. Go to 'start'
2. Click on 'Screenbox'
3. load ande close

**Expected behavior**

**Screenshots**

**Environment**

 - OS: Windows 11 Home
 - Device:  Laptop 6 Go Ram
 -  - App Version 0.12.7.0

**Additional context**

**Comment by huynhsontung** [comment]
After reviewing recent error reports. I suspect the new library change tracker is throwing exceptions on some machines. Should be fixed in #382 and 6b59e2a74b479e548f62ce382e4d3a655a73ffd3. A new update is going up soon.

**Comment by huynhsontung** [comment]
This issue should be fixed in v0.12.8. Closing this PR. Feel free to reopen if you still encounter this issue after updating.
