### ISSUE TITLE
Symlink Scanning Support

### ISSUE THREAD

**Issue by D-Maxwell** [huynhsontung/Screenbox#398]
**Describe the bug**
It would seem that Screenbox lacks the ability to scour symlinks to directories ; which in the case of NT, would rather be "junctions to folders". (NT does seem to treat the two differently in some way that I remain unaware of, although Screenbox refuses to acknowledge the existence of either of those)

**How To Reproduce**
Create a junction to any folder.
Witness Screenbox's inability to consider the junction for its target's value.

**Expected behavior**
I would be expecting the scanning to take potential symlinks into account and evaluate those to scan through their target location(s).

**Screenshots**
![image](https://github.com/huynhsontung/Screenbox/assets/98100481/887795e8-d5a2-47e6-80dc-6cfa803f1df5)
![image](https://github.com/huynhsontung/Screenbox/assets/98100481/4f44efb2-04bc-4003-8913-1b4c835ef215)

**Environment**
 - OS: Windows 10 (NTFS)
 - Device: Desktop PC
 - App Version [e.g. v0.12.8]

**Additional context**
(note : this is unrelated to my initial guess, which had to do with the target directories residing in a separate drive from their pointers)

**Comment by huynhsontung** [comment]
Hello, symlinks are not supported by the current UWP capability. This is a platform restriction/limitation. The expected method of adding directories to your videos library is by using the "Add folder" button on the settings page or at the top of the Videos page to browse and select the directories you want to scan.

![image](https://github.com/huynhsontung/Screenbox/assets/31434093/cce8bb51-29c2-4a01-be56-9d26cb7d1c32)

**Comment by D-Maxwell** [comment]
> Hello, symlinks are not supported by the current UWP capability. This is a platform restriction/limitation.

That is certainly unfortunate. What is most odd is that I am aware of another UWP app --[Files](https://github.com/files-community/files/)-- which is in fact able to, even if not recognising those as symlinks (or so it would seem, as the GUI lacks any information indicative of that), consider symlinks and junctions for their target folder in place of themselves.

**Comment by huynhsontung** [comment]
AFAIK Files is no longer an UWP app anymore. They have fully migrated to WinAppSDK/WinUI3 and extensively make use of Win32 APIs to get good files performance. Is there any benefit for using symlink in your libraries? Wouldn't it be the same to add the folder in the app instead?

**Comment by D-Maxwell** [comment]
> AFAIK Files is no longer an UWP app anymore. They have fully migrated to WinAppSDK/WinUI3 and extensively make use of Win32 APIs to get good files performance. Is there any benefit for using symlink in your libraries? Wouldn't it be the same to add the folder in the app instead?

I structure my drives following a single directory pattern. I have a script that updates a single junction to map it to all available directories in each plugged drive.
Now this is an extremely specific use case ; but I wish it could be made fully modular, without requiring me to manually add each subdirectory for each drive I have plugged in.

**Comment by huynhsontung** [comment]
Due to platform limitations, this feature requires quite a considerable amount of work for quite a narrow use case. Unless we need to use Win32 file API down the line for something, we will likely not implement this capability.
