### ISSUE TITLE
Translation pt-BR is cut off in video viewing mode while listening to music 

### ISSUE THREAD

**Issue by maisondasilva** [huynhsontung/Screenbox#401]
The translation is cut off in video viewing mode while listening to music!
in my language pt-BR there was only one letter missing and the final border!

![image](https://github.com/huynhsontung/Screenbox/assets/11423362/6ce512fe-e420-44e5-8c1e-c8afca552f6d)

**Comment by United600** [comment]
Oh yeah, I've been meaning to fix that by converting to AppBarButton and place them in a CommandBar.

**Comment by huynhsontung** [comment]
I plan to change the remove and multi select buttons to icons only
