### ISSUE TITLE
Misaligned Hamburger Menu

### ISSUE THREAD

**Issue by SteadfastWhiplash** [huynhsontung/Screenbox#409]
On launch the hamburger menu is a few pixels too far to the right. It resets to a correct position after pressing the button once with the app open.

1. Open the app.
2. Look at highlighted hamburger menu at top left.

It should be aligned with the other buttons.

![Screenshot 2024-07-27 224433](https://github.com/user-attachments/assets/743f6195-59d4-4f8d-8a77-228aa17eb370)

 - OS: Windows 11 IoT Enterprise LTSC
 - Device: PC
 - App Version 0.12.8.0

**Comment by huynhsontung** [comment]
This is an issue with WinUI unfortunately.
https://github.com/microsoft/microsoft-ui-xaml/issues/9034

**Comment by SteadfastWhiplash** [comment]
As of April 2026 still an issue. Haven't seen this in any other WinUI apps. There has to be some possible fix to implement here. Maybe while opening the application to automatically and instantly open the hamburger/open and close it on launch. 

<img width="46" height="83" alt="Image" src="https://github.com/user-attachments/assets/3b831f12-5333-4a87-85a9-4d1c1add8155" />
