### ISSUE TITLE
Crash on library access denied

### ISSUE THREAD

**Issue by ShinsuSenju** [huynhsontung/Screenbox#41]
Crash after opening the app. Directly playing video works but accessing the app leads to crash
Using 

- Windows 11 insider preview ( Canary)

**Comment by huynhsontung** [comment]
I just checked the recent crash report. It looks like you the app is trying to access your video library but got an access denied exception. Did you block the app access to the video library by any chance?

Also I should handle this exception better. Thanks for the report.

**Comment by ShinsuSenju** [comment]
No I don't think so.... I just installed app and did nothing except opening it

**Comment by ShinsuSenju** [comment]
Okay, the is related to video library access.
This option is disabled by default on windows
Turning On the option **"Let apps access your videos library"** for **Privacy and Security** -> **Videos** fixes the problem
