### ISSUE TITLE
Play multiple audio tracks at once

### ISSUE THREAD

**Issue by Armin2208** [huynhsontung/Screenbox#42]
Screenbox is a great project, hands down for this good work and concept!

I am recording gameplay with two audio tracks. Audio track 1 is my game sound and audio track 2 is my voice/microphone input. With VLC Media Player I can play both at once with a little bat-file:
start "" "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --sout-all --sout #display %1%

Would be a nice feature from Screenbox if it would support play multiple audio tracks of one video file at once. Would be a killer feature for video creators. This is the only reason I use VLC beside of the supported codecs.

Thanks!

**Comment by huynhsontung** [comment]
This is finally possible. To play multiple audio tracks at once, right click on item and select "Set playback options". A dialog will show up for you to enter VLC arguments.

![image](https://github.com/huynhsontung/Screenbox/assets/31434093/8cf8ccc9-8d62-4bbc-bc73-26c9d43c32ba)

**Comment by Armin2208** [comment]
Hey @huynhsontung,

firstly thanks for implementing the advanced mode. Being able to run libvlc command line arguments is awesome and powerful.

But I am not able to play all audio tracks from a video at once. I've tried some variations of the argument:

--sout-all --sout=#display
--sout-all
--sout-all --sout:#display (throws error)
:sout-all :sout=#display (doesn't get saved, probably wrong syntax in the stable version)

All these arguments don't work either set in settings and directly open a file, or setting it per individual file in Screenbox and then playing it.

I assume, without knowing the code, that Screenbox always enforces playing an specific audiotrack at the start of a playback. So the command line argument sout-all is useless.

**Comment by huynhsontung** [comment]
Hi @Armin2208,

Thanks for letting me know. I have tested this use case specifically by setting these arguments on the media file.

`:sout-all :sout=#display`

 Due to LibVLC limitations, you can only apply the arguments to play all audio tracks per media file. They won't do anything when set globally in the Settings. You would need to set the arguments on every file and they are not persistent (I don't think they should? Let me know if it makes more sense to keep the arguments across sessions). 

Note that this would play all audio tracks at max volume and you cannot change that volume in UI.

**Comment by Armin2208** [comment]
Thanks for explaining the different syntax of global args and media specific args. This makes sense!

I've tried using `:sout-all :sout=#display `with a specific media file and it worked like a charm. Awesome!

> You would need to set the arguments on every file and they are not persistent (I don't think they should? Let me know if it makes more sense to keep the arguments across sessions).

I don't think media specific args need be persistent. But I can imagine some people will expect this behaviour, so it would be an useful addition.

There is something else that would help me more. The ability to open a file directly from it's folder, then clicking on the three dots and selecting the new option "Set playback options" from the playback menu. This would help playing videos with sout-all directly from Windows Explorer, without needing to add more video folders to Screenbox. After clicking on Set playback options, the existing popup should display and "Set and play" should then reopen the same video just with the args. Maybe in this case it would help if Screenbox is at least displaying the last used media specific arg as placeholder.

**Comment by huynhsontung** [comment]
> There is something else that would help me more. The ability to open a file directly from it's folder, then clicking on the three dots and selecting the new option "Set playback options" from the playback menu. This would help playing videos with sout-all directly from Windows Explorer, without needing to add more video folders to Screenbox. After clicking on Set playback options, the existing popup should display and "Set and play" should then reopen the same video just with the args. Maybe in this case it would help if Screenbox is at least displaying the last used media specific arg as placeholder.

Absolutely. This is a great enhancement for the feature. I have a similar vision for this interaction but did not have enough time to work out all the kinks. Tracking this change here #156
