### ISSUE TITLE
Unintended UI flipping in right-to-left languages

### ISSUE THREAD

**Issue by Y-PLONI** [huynhsontung/Screenbox#429]
The image is displayed upside down, here is a screenshot in Windows Media Player
![image](https://github.com/user-attachments/assets/af06008f-d24a-480e-96e1-bdd802e8dca6)
And here is a picture from Screenbox
![image](https://github.com/user-attachments/assets/e5be240d-a339-42c2-a89c-fec5e1fd3645)
As I wrote here:
https://github.com/huynhsontung/Screenbox/issues/418#issuecomment-2309680883
The problems are that the application is configured in Windows in Hebrew mode and the operating system creates RTL for everything possible, including what is not needed...
In my opinion, if possible, you should set the application as English, and only the text in it will be in Hebrew.
If not possible, write to me and I will try to investigate the issue!

I use Windows 11, the latest version of the app released in the store.

**Comment by huynhsontung** [comment]
In the right-to-left language, are the window control buttons (minimize, maximize, close) on the left or the right of the window? There shouldn't be any navigation issue right? 

![ApplicationFrameHost_pb11w8588E](https://github.com/user-attachments/assets/1aabe835-f98d-4348-92e5-798c9968d463)

I did not expect WebView and SwapChainPanel to get flipped by RTL as well...

![ApplicationFrameHost_FNdFmfKiCt](https://github.com/user-attachments/assets/95e0c266-7312-4fc0-9e17-44425d599a60)

![Screenshot 2024-08-26 022505](https://github.com/user-attachments/assets/1b426b44-f8dc-40bd-9c84-9949d99fb60a)

Fortunately, the solution is straightforward. I can force certain elements to not flip. Just as I can apply RTL even in English.

**Comment by huynhsontung** [comment]
Forcing WebView and VideoView to always flow LTR.

https://github.com/user-attachments/assets/f9dd334f-9f8b-4282-b429-2238e43b6818

@Y-PLONI Are there more UI elements or layouts that you think look off in Hebrew? Do the sliders and buttons behave correctly, and are they in the expected spots?

**Comment by Y-PLONI** [comment]
![image](https://github.com/user-attachments/assets/6ce2d53c-e14c-4f2b-bfca-6e7590992495)
![image](https://github.com/user-attachments/assets/86f706e2-c251-4265-9b67-c9daf9c77bf7)

**Comment by Y-PLONI** [comment]
Can you force normal view in both windows store and file explorer?
Right now the situation is that things are changing there...
here:
![image](https://github.com/user-attachments/assets/249d56ee-3ff2-4704-a745-a1f343f52fd6)
I assume you don't know Hebrew, so I'll just explain that the word Screenbox should have been at the beginning. Also note the position of the "."
I was thinking of just changing everything in the translation... I mean, pushing the words so that they are in the correct position after Windows flips them... but if you have the ability to force, everything will be easier.

**Comment by United600** [comment]
> ![image](https://private-user-images.githubusercontent.com/116633732/361405152-6ce2d53c-e14c-4f2b-bfca-6e7590992495.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODcwNjksIm5iZiI6MTcyNDY4Njc2OSwicGF0aCI6Ii8xMTY2MzM3MzIvMzYxNDA1MTUyLTZjZTJkNTNjLWUxNGMtNGYyYi1iZmNhLTZlNzU5MDk5MjQ5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxNTM5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzJkZjEwY2YwOWFmMGU0ZmNmZjI3Y2YxNjk1OTAzMWE5ODIxNWM3ZmYxMWE0ZjMwMjViYTgzZjNjOWRiMThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TPmjgn8O1MPQXtvM3IrRWDX5PioVt_1O78ee5_GOkB4) ![image](https://private-user-images.githubusercontent.com/116633732/361405639-86f706e2-c251-4265-9b67-c9daf9c77bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODcwNjksIm5iZiI6MTcyNDY4Njc2OSwicGF0aCI6Ii8xMTY2MzM3MzIvMzYxNDA1NjM5LTg2ZjcwNmUyLWMyNTEtNDI2NS05YjY3LWM5ZGFmOWM3N2JmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxNTM5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzU0ZGQ4N2UwMTJiY2MzYmJlYzEzYThmOTY4MGMxNzA4ZDQyYmNkZWQwNzA0M2MyMDRiYTM2YTczZjIyNDMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9dH_H46zMafxIEfHU5pfVJUuW8gUzwDFG9W4CPhJhP8)

I see we don't flip the icons, we should for most of them right?

Also we have to take into consideration the backslash on some of them. Like this:

![Shuffle icon and it's mirrored counterpart](https://github.com/user-attachments/assets/19e21631-0cca-44ab-8332-12bdc149659f)

**Comment by Y-PLONI** [comment]
> I see we don't flip the icons, we should for most of them right?
> 
> Also we have to take into consideration the backslash on some of them. Like this

I didn't understand what you meant. Can you explain more?

**Comment by United600** [comment]
> I didn't understand what you meant. Can you explain more?

Forgive my limited knowledge on this area, but I recall that some icons need to be flipped (e.g. the volume glyph, etc.) and after reviewing some documentation it seems to confirm that (except for those indicating directionality and right handedness).

**Comment by huynhsontung** [comment]
@Y-PLONI Can you take a look at #434 to see if that looks right to you?

**Comment by Y-PLONI** [comment]
@huynhsontung Looks great!
Of course, until you see it in the software itself - you can't know clearly...

**Comment by Y-PLONI** [comment]
@huynhsontung Is there a release with the fix, or not?
I didn't see any update in Windows Store.

**Comment by huynhsontung** [comment]
@Y-PLONI Yes, there will be a new release. Store publishing takes from a few hours to a few days. It's going to be available for download in the preview channel first, then in the main public channel later. I will also fix the store listing when it goes into the public channel.

**Comment by Y-PLONI** [comment]
How do you subscribe to the preview channel?

**Comment by huynhsontung** [comment]
@Y-PLONI I must add your Store account on my end using your Store email. You can send me an email at tung75605@live.com

**Comment by Y-PLONI** [comment]
I suggest you enter in the settings "Subscribe to the preview channel". It could be MAILTO.

**Comment by Y-PLONI** [comment]
@huynhsontung 
Everything is great, just a little something...
![image](https://github.com/user-attachments/assets/5b86fcbf-a1a6-443e-a5df-210ac296a64c)

**Comment by Y-PLONI** [comment]
@huynhsontung 
Could you please add RTL here? thanks! I have already installed the app on several computers... everyone loves it!!!
![image](https://github.com/user-attachments/assets/b6473bb9-4ed4-47db-8213-90acce83fd43)

**Comment by Y-PLONI** [comment]
By the way, I couldn't find where to translate the titles media, music, fi

**Comment by huynhsontung** [comment]
@Y-PLONI You are right, the header texts for Media, Music, File are not properly localized. It will be fixed in the next patch.

I also just noticed that the title bar offset issue affects the app title and the player title bar, which is quite serious. In LTR, that space is reserved for the window controls. I'm surprised that it doesn't get flipped properly, considering if I force-enable RTL in English, the issue does not appear.

![image](https://github.com/user-attachments/assets/21604085-6583-47a2-9135-eb14870a21f4)
![image](https://github.com/user-attachments/assets/15e03ed8-63f3-4e9f-8e76-f97d11a0fa15)

**Comment by Y-PLONI** [comment]
@huynhsontung 
True, but it doesn't matter. The window controls just move to another place.
Are there any other controls that are disappearing?
I would love to see a screenshot of the software, as it looks on you.

**Comment by huynhsontung** [comment]
@Y-PLONI The above PR should fix the title bar padding issue and properties dialog RTL issue.

**Comment by Y-PLONI** [comment]
@huynhsontung 
why is it in english Where should I translate it?
![image](https://github.com/user-attachments/assets/4c201aa6-5574-407f-9a2f-f33d51eb9a78)
Thank you very much!!!

**Comment by huynhsontung** [comment]
@Y-PLONI These errors are emitted from VLC and shown as-is. We don't map them to a localized string so translation is impossible.

**Comment by yarons** [comment]
@huynhsontung It's a good call but there's an alternative solution: adding a human readable translatable explanation to the original error message, this way the user can still search for the original message and find solutions on the internet while understanding the error in it's own language.
(Thanks @Y-PLONI)

**Comment by Y-PLONI** [comment]
The top image is correct, the bottom is reversed.
It was fine before. Something went wrong with the update.
Also in the song playback window the image is reversed.
![image](https://github.com/user-attachments/assets/57ff7472-f8f6-4e5c-9f9e-763b81e58b75)

![image](https://github.com/user-attachments/assets/e7382d78-53fb-4f17-920d-1b0958533df9)

**Comment by huynhsontung** [comment]
Version 0.14.1 with a fix for image flipping has been published. Please open a new issue and link to this one if there are other right-to-left issues.

**Comment by Y-PLONI** [comment]
![image](https://github.com/user-attachments/assets/0fd100be-884f-486c-aaa2-0f46028c986b)
Great!!!
