### ISSUE TITLE
Gesture support

### ISSUE THREAD

**Issue by aquaredtea** [huynhsontung/Screenbox#439]
Hello. Is that possible to turn off gesture support? It is not very convenient to change the volume and seeking with the mouse

**Comment by Mitia99** [comment]
Volume gesture control is already supported

![image](https://github.com/user-attachments/assets/44beba18-b6d9-431a-8e77-f8a7a41da2b9)

These gestures aren't supported yet

- Brightness control and zoom #219
- Double tap to seek #227

**Comment by aquaredtea** [comment]
my bad, I forgot to check the application settings and searched for it in Windows Installed Apps > Screenbox. thanks a lot ❤️
