### ISSUE TITLE
UWP will be depricated!

### ISSUE THREAD

**Issue by Jackson-Nickk** [huynhsontung/Screenbox#452]
According to Microsoft, UWP while still supported, will not be developed anymore: [What's a Universal Windows Platform (UWP) app?](https://learn.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide) (the note on top of the article)

Is there any plans for migrating to WinUI in the future?

![Screenshot 2024-09-26 121854](https://github.com/user-attachments/assets/5ef16352-2cca-445d-8d6b-4da32c9c02c5)

**Comment by huynhsontung** [comment]
No plan to migrate to WinUI at the moment. Screenbox is still targeting Xbox, which is not supported by WinUI. Besides, saying UWP is deprecated is misleading. It doesn't get active support but it doesn't mean it will stop working one day. It will receive the same kind of treatment that Microsoft gave to WinForms and WPF for example. WinForms and WPF are not going anywhere. WinUI is just not mature enough to be considered as a migration path.

Microsoft just [announced](https://devblogs.microsoft.com/ifdef-windows/preview-uwp-support-for-dotnet-9-native-aot/) they will be bringing .NET 9 to UWP with NativeAOT support. I will skip this preview and wait for the coming ones when it's a bit more mature.
