### ISSUE TITLE
Music pt-BR

### ISSUE THREAD

**Issue by maisondasilva** [huynhsontung/Screenbox#457]
Hello, in our language pt-BR there is Musica and Musicas which are the same translation for Music, is it possible to change the translations to Music Libraries and Video Library?

![image](https://github.com/user-attachments/assets/3cfe0277-0130-4ef4-9925-068d104bfc13)

Or he can take the "Songs" variable which in my language is Music(Música) too!

(Header="{strings:Resources Key=Music}")

https://github.com/huynhsontung/Screenbox/commit/6c58d26b96bca0693639a02a3687c664fd1cbd24#diff-e9758c7d41b1c328d9a629cf03bf33560a665ca2f593672b66574013ec971593R98

**Comment by maisondasilva** [comment]
@huynhsontung

**Comment by maisondasilva** [comment]
@huynhsontung Thank you, I have already corrected the translation! 🎉🥳

**Comment by maisondasilva** [comment]
@huynhsontung I have a question, I see that in video there are three variables: videos and VideoLibrary, is it just me or does Videos do the same function as VideoLibrary now? Should Videos be removed?

![image](https://github.com/user-attachments/assets/8983ec01-8849-480c-81dc-b66d6f970a6a)

**Comment by huynhsontung** [comment]
@maisondasilva The Video (singular) string is for the media properties dialog. VideoLibrary is for the Videos page headers. Videos (plural) is for the search results page. I may have jumped the gun by separating VideoLibrary into its own string. Oh well.

![image](https://github.com/user-attachments/assets/01b802e2-bf70-47ee-97c6-7d4950771253)
![image](https://github.com/user-attachments/assets/5b077ff4-1b69-4c7f-bc0a-63ff225e49ce)

**Comment by maisondasilva** [comment]
@huynhsontung It looks really good now, thanks for the heads up, I've already fixed them all!
