### ISSUE TITLE
Invert the order of the side menu, place the music library before the video library.

### ISSUE THREAD

**Issue by maisondasilva** [huynhsontung/Screenbox#462]
Invert the order of the side menu, place the music library before the video library.

![image](https://github.com/user-attachments/assets/8cf97013-310a-4150-98bc-16e0b614fc1d)

**Comment by United600** [comment]
Does it really make any difference? In the present, I would say that this app is primarily a video player and the order reflects that

**Comment by huynhsontung** [comment]
Is there a reason for this change?

**Comment by maisondasilva** [comment]
I usually access my music playlist in screenbox and I usually open videos directly from the files.
Furthermore, it follows the same pattern as the Windows player.

![image](https://github.com/user-attachments/assets/be516eae-dcdf-4840-a7d9-8221904a0775)

**Comment by United600** [comment]
I'm not enterily against it, we just need to decide on the ordering. Should we prioritize by most used or go alphabetically?

**Comment by maisondasilva** [comment]
I think just this change would be good!
