### ISSUE TITLE
Adjust audio delay (offset)

### ISSUE THREAD

**Issue by Mitia99** [huynhsontung/Screenbox#469]
**Is your feature request related to a problem? Please describe.**
I have a video file with unsynced audio and image

**Describe the solution you'd like**
Option to adjust audio delay (offset)

**Additional context**
Feature available in VLC UWP

![image](https://github.com/user-attachments/assets/ddabf818-b4a3-496b-9607-6ba906eb9891)

Screenbox should remember the custom offset when playing the file again.

Thanks for considering this,

**Comment by huynhsontung** [comment]
This is implemented in #442 and will be available in v0.14.0
