### ISSUE TITLE
Subtitle Selector should open up the folder the media was opened from

### ISSUE THREAD

**Issue by thisisartman** [huynhsontung/Screenbox#481]
**Describe the bug**
Whenever I want to add a subtitle file, the app opens up the previous folder that I selected a subtitle from instead of the folder that I'm currently opening the file from.

**How To Reproduce**

**Expected behavior**
It should open up the folder that media file was opened from.

**Screenshots**

https://github.com/user-attachments/assets/8e589270-9556-4319-80ed-d51abf7ca214

**Environment**

 - OS: Windows 11 Pro 24H2 26100.2033
 - Device: Acer Predator Triton 300
 - App Version: 0.14.1.0

**Additional context**
Attaching the VLC Media Player behaviour for further context:

https://github.com/user-attachments/assets/3fe25d3a-4498-45ac-8d34-a409c2c9e106

**Comment by huynhsontung** [comment]
Unfortunately, this is a limitation of the UWP API. We cannot directly set the start path of the open file picker. The picker can start with only a few supported locations.

https://learn.microsoft.com/en-us/uwp/api/windows.storage.pickers.pickerlocationid
