### ISSUE TITLE
bit32 software

### ISSUE THREAD

**Issue by Y-PLONI** [huynhsontung/Screenbox#483]
Can you compile the software into a 32-bit EXE?
I have a very very old tablet, on which the Windows Store no longer works... [Windows 10 version 1511...]
Thank you very much!

**Comment by huynhsontung** [comment]
You can download an msixbundle installer from the release page. You can use that file to install on Intel 32 bit (x86_64), AMD 64 bit (amd64), and arm64 machines. The app does not support arm32 architecture however.

https://github.com/huynhsontung/Screenbox/releases/tag/v0.14.1

If you cannot open the msixbundle file then it's likely that your Windows version is too old.

**Comment by huynhsontung** [comment]
In your case, Windows 10 1511 is too old to run Screenbox. The app needs Windows 10 1903 or higher.
