### ISSUE TITLE
Would be nice if unpackaged .exe program was available.

### ISSUE THREAD

**Issue by BitsOfSreehari** [huynhsontung/Screenbox#490]
**Is your feature request related to a problem? Please describe.**
When the file is being downloaded, let's say from it may temporarily have a unconventional extension. So we can't direct open the file with Screenbox from context menu.

**Describe the solution you'd like**
Would be nice if Screenbox is made availalable as a unpackaged .exe program. So that we can do 'open with Screenbox' on any file regardless of it's extension being wrong or changed without explicitly associating the extension with Screenbox.

**Describe alternatives you've considered**
Well I can just open the file after opening Screenbox :)

**Additional context**
I did see other request about the same and one of your reply was "This is not currently planned as there are no inherent benefits to having an unpackaged .exe program. Unpackaged will also add complexity to the app installation. Are there any particular reasons you wish for the app to be a .exe executable?". I completely understand that so do it only if you got time or if you think it's worth it :)

**Comment by United600** [comment]
In theory, we could include Screenbox in the "Open with" suggestions, but I don't believe it's the best approach for a media player app. Also if you don't know, you can simply drop any file into the app to play it.

If you have an file extension that has been verified to work correctly feel free to request its inclusion.
