### ISSUE TITLE
The latest version(0.14.2.0) cannot start normally

### ISSUE THREAD

**Issue by Wwyxa** [huynhsontung/Screenbox#499]
**Describe the bug**

After updating to the latest version of the software can not start, the specific performance: open the software appears only blue window, and then will flash

**How To Reproduce**

Appears after updating to the latest version (0.14.2.0), the previous version is normal

**Expected behavior**

Normal opening of software

**Screenshots**

Open the software only this window appears, and then it will flash back
![image](https://github.com/user-attachments/assets/599c3d67-2c1a-4aa0-8b24-59c0cb2594ab)

**Environment**

 - OS: Windows 10 professional 22H2
 - Device: PC
 - App Version: 0.14.2.0

**Additional context**

**Comment by huynhsontung** [comment]
We are aware of this problem. There is a serious bug with Windows 10 on the latest app version. We are looking into it.
