### ISSUE TITLE
Window Resizing Problem

### ISSUE THREAD

**Issue by Y-PLONI** [huynhsontung/Screenbox#511]
When playing a video in SCREENBOX, the window resizes correctly to fit the media. However, after switching to audio playback, the window remains large and does not resize.

I thought to propose setting a default window size for audio playback and ensuring the window automatically adjusts to the dimensions of the video when playing video content.

**Comment by United600** [comment]
Duplicate of #414

**Comment by Y-PLONI** [comment]
You are right, thank you!!!
I'm closing.
