### ISSUE TITLE
Add drag and drop support on playlist

### ISSUE THREAD

**Issue by rony747** [huynhsontung/Screenbox#65]
Please add drag and drop support on the playlist so that  we can rearrange the order of videos, add or remove videos from the playlist

**Comment by huynhsontung** [comment]
The playlist has always had drag and drop support to reorder items.
![ApplicationFrameHost_6PRxsH2nNu](https://github.com/huynhsontung/Screenbox/assets/31434093/753f2d11-e394-4cda-9db1-a39893f5b0a1)

You can drag files into the "Play queue" page to add them to the playlist.

#69 also added the ability to drag and drop files into the playlist flyout.

![ApplicationFrameHost_yAGMwDYSXj](https://github.com/huynhsontung/Screenbox/assets/31434093/75e8588b-e2d1-4458-8bf4-d40a4dd823ca)

**Comment by huynhsontung** [comment]
Close the issue for now. Feel free to reopen if I miss anything.
