### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [huynhsontung/Screenbox#98]
Does this work with Win 7?

Thanks

**Comment by DARO75** [comment]
NO! Universal Windows Platform (UWP)  only Windows 10- and Windows 11

**Comment by huynhsontung** [comment]
Short answer: No, and likely never will.

Screenbox is built on top of the UWP app model which utilizes a lot of WinRT APIs that simply don't exist on Windows 7. On top of that, Screenbox also depends on many libraries that have limited down level support so the official requirement for Screenbox is Windows 10 1903 build 18362 and up.

For Windows 7, if you prefer the modern aesthetic, I recommend taking VLC 4.0 for a spin.
