### ISSUE TITLE
Couldn't install the new Sideload 

### ISSUE THREAD

**Issue by animegamer4422** [huynhsontung/Screenbox#99]
when i try to install the package through the provided install.ps1 i get the following error
and also i cannot delet those pri files and other copies of the application as it says access denied

here's the actual error

❯ .\Install.ps1 /Force /SkipLoggingTelemetry
Found bundle: D:\screenbox\download\Screenbox\Screenbox_0.9.7.0_x86_x64_ARM.msixbundle
Found certificate: D:\screenbox\download\Screenbox\Screenbox_0.9.7.0_x86_x64_ARM.cer

Before installing this app, you need to do the following:
        - Install the signing certificate
Administrator credentials are required to continue.  Please accept the UAC prompt and provide your administrator password if asked.
Press Enter to continue...:
The certificate was successfully installed.

Installing app...
Add-AppxPackage: Deployment failed with HRESULT: 0x80073CF6, Package could not be registered.

Merge failure for shared merged PRI file : error 0x80070490 : Cannot register the 18496Starpine.Screenbox_0.9.7.0_x64__rm8wvch11q4my package because there was a merge failure with the following file: C:\Program Files\WindowsApps\18496Starpine.Screenbox_0.9.7.0_neutral_split.scale-125_rm8wvch11q4my\resources.pri

NOTE: For additional information, look for [ActivityId] a2f282e3-ab83-000d-57aa-c5a383abd901 in the Event Log or use the command line Get-AppPackageLog -ActivityID a2f282e3-ab83-000d-57aa-c5a383abd901
Error: Could not install the app.  To ensure security, please consider uninstalling the signing certificate until you can install the app.  Instructions for doing so can be found here:
http://go.microsoft.com/fwlink/?LinkId=243053
Press Enter to continue...:

**Comment by huynhsontung** [comment]
Hello, this seems like an issue with app packaging. Thank you for reporting. Please use this link to try again. Let me know if this works.

https://github.com/huynhsontung/Screenbox/releases/download/v0.9.7/Screenbox_0.9.7.0_x64.zip

**Comment by animegamer4422** [comment]
now i'm encountering this error related to a certificate

❯ .\Install.ps1
Found bundle: C:\Users\$USERNAME\Downloads\Screenbox_0.9.7.0_x64\Screenbox_0.9.7.0_Test\Screenbox_0.9.7.0_x64.msixbundle
Error: The package or bundle is not digitally signed or its signature is corrupted.
Press Enter to continue...:

**Comment by huynhsontung** [comment]
My bad, try this one instead

https://github.com/huynhsontung/Screenbox/releases/download/v0.9.7/Screenbox_0.9.7.0_Test.zip

**Comment by animegamer4422** [comment]
Yup that worked
BTW Thanks for Building such a Beautiful app

❯ .\Install.ps1
Found bundle: C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Screenbox_0.9.7.0_x64.msixbundle
Found certificate: C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Screenbox_0.9.7.0_x64.cer

Before installing this app, you need to do the following:
        - Install the signing certificate
Administrator credentials are required to continue.  Please accept the UAC prompt and provide your administrator password if asked.
Press Enter to continue...:
The certificate was successfully installed.

Installing app...
Found dependency package(s):
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.NET.Native.Framework.2.2.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.NET.Native.Runtime.2.2.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.UI.Xaml.2.8.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.12.00.Universal.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.Desktop.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.UI.Xaml.2.8.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.12.00.Universal.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
C:\Users\Hari\Downloads\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.Desktop.appx

Success: Your app was successfully installed.
Press Enter to continue...:

![81](https://github.com/huynhsontung/Screenbox/assets/71986052/d3fb1b13-2db9-47ae-86d5-d8b6c563524a)

**Comment by animegamer4422** [comment]
Wait on my windows 11 machine i'm still getting the error

.\Install.ps1
Found bundle: D:\APPS\Screenbox_0.9.7.0_Test\Screenbox_0.9.7.0_x64.msixbundle
Found certificate: D:\APPS\Screenbox_0.9.7.0_Test\Screenbox_0.9.7.0_x64.cer

Before installing this app, you need to do the following:
        - Install the signing certificate
Administrator credentials are required to continue.  Please accept the UAC prompt and provide your administrator password if asked.
Press Enter to continue...:
The certificate was successfully installed.

Installing app...
Found dependency package(s):
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.NET.Native.Framework.2.2.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.NET.Native.Runtime.2.2.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.UI.Xaml.2.8.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.12.00.Universal.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.Desktop.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.UI.Xaml.2.8.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.12.00.Universal.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage: Cannot find path 'D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.NET.Native.Framework.2.2.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.NET.Native.Runtime.2.2.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.UI.Xaml.2.8.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.12.00.Universal.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.Desktop.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.UI.Xaml.2.8.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.12.00.Universal.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx D:\APPS\Screenbox_0.9.7.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.Desktop.appx' because it does not exist.
Error: Could not install the app.  To ensure security, please consider uninstalling the signing certificate until you can install the app.  Instructions for doing so can be found here:
http://go.microsoft.com/fwlink/?LinkId=243053
Press Enter to continue...:

**Comment by animegamer4422** [comment]
The certificate issue doesn't exists anymore but the dependencies issue still does

maybe it's parsing the path wrong
because i looked into the x86 and x64 folder and the dependencies do exist

**Comment by animegamer4422** [comment]
ok i just used the MSIXBUNDLE and it installed right away
Thanks

**Comment by huynhsontung** [comment]
Glad it works out. I will update the sideload packaging in CI later. Closing this issue.
